name: Caching and Artifacts

on: [workflow_dispatch]

jobs: 
  use-axios:
    runs-on: ubuntu-latest
    steps:
      # In order to create a Cache these are the basic steps.
      # When caching, this allows to make the workflows to run faster, because it does not need to
      # reinstall all the dependencies every single time the workflow runs.
      - uses: actions/checkout@v3
      - name: Cache Node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # the problem when using static keys, is that when adding a new package, this packafge will not 
          # be considered in the existing cache.
          # key: "npm-cache"
          # So, in order to make the cache dynamic, we need to include the package.json as an expression into the key
          # We can also have a different cache for every single OS
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          # In the case we do not find a key, then we can rely on restore-keys. It does not have to be an exact string.
          # we can provide only certain part of the string to look after.
          restore-keys: |
            ${{ runner.os }}-npm-cache-$
            ${{ runner.os }}-
      - name: Display Cache output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'

      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test

      # How to create an artifact
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        if: always() # Even if the test fail, the coverage report is gonna be generated
        with: 
          name: code-coverage # We can provide a name to the artifact
          path: coverage
          retention-days: 10 # what time are the artifacts will live in the storage

      - name: Use Axios
        uses: actions/github-script@v6
        with: 
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', {headers: {
              Accept: 'text/plain'
            }});
            console.log(res);