name: Checkout 
# How to migrate the current files of the repository to the RUnner Machine of the Workflow

on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files before
        run: ls -a
      - uses: action/checkout@v3
      - name: List Files after
        run: ls -a
        
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files before
        run: ls -a
        # GITHUB_ACTOR => current username, settled default by GitHub
        # ${{ secrets.MYSECRET }} => way to access to the SECRETS created in the repository. 
      - name: Chekcout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" 
          git fetch origin
          git checkout main
      - name: List Files after
        run: ls -a
    