name: Concurrency 2
run-name: Concurrency 1 (${{ inputs.environment }})

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true

# If two different workflows have the same concurrency group, they can interfere with each other.
concurrency: 
  # add the workflow name, so we can have 2 different concurrency groups.
  group: ${{ github.workflow }} - ${{ github.event.inputs.environment }} 
  cancel-in-progress: true

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30