name: Expressions & Contexts

on: [push, pull_request, issues, workflow_dispatch]

# Way to indicate the name of the contributor and the actior they performed.
run-name: "Expressions & Contexts BY @${{ github.actor }}, event: ${{ github.event_name }}"

jobs: 
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    # IF is placed at runs-on level
    # the ${{}} is not necessary. Everything inside the IF is treated as an expression.
    if: github.event_name == 'push'
    steps:
      # yaml is not case sensitive
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'I am a String' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }} 
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      # Basic contexts
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'