name: First Workflow

# On: => what triggers the Workflow
on: [push]

jobs:
  run-shell-commands: 
    runs-on: ubuntu-latest #indicates the OS for the Runner Machine
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline command
        run: | # | => Used in order to run multiple commands in one step
          node -v
          npm -v

  parallel-job-macos:
    runs-on: macos-latest
    steps: 
      - name: View SW Version
        run: sw_vers

  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands #this indicates that this Job will only run after the run-shell-commands have finished.
    steps: 
      - name: echo a string
        run: Write-Output "Windows String" # Because we are talking about windows, the expected command is in PowerShell syntax
      - name: Error step
        run: doesnotexists # In order to trigger an Error => The term 'doesnotexists' is not recognized as a name of a cmdlet, function, script file, or executable program.
