name: Matrix
on: [push]

jobs: 
  node-matrix:
    runs-on: ubuntu-latest
    # The strategy defines the matrix, so as many arguments are received, is the number of times the job will run
    # each time with one of the given values.
    strategy:
      matrix: 
        node-version: [14, 15, 16]
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v
