name: Matrix
on: [push]

jobs: 
  node-matrix:
    # at job level, if any step fails, the whole job is not interrupted.
    # continue-on-error: true
    continue-on-error: ${{ matrix.experimental == true }}
    
    # The strategy defines the matrix, so as many arguments are received, is the number of times the job will run
    # each time with one of the given values.
    # In the case of having more than 1 defined matrix, then the job will run with all the possible combinations.
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
        include: 
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            node-version: 15
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: ubuntu-latest
            node-version: 14

      #------- ORIGINAL --------#
      # When defining an include, this will try to catch all the matches, if no matches exist, it will create/include the mentioned
      # option in the matrix. 
      # X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
      # {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
      # {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
      # {os: windows-latest, node-version: 14, experimental: false}
      # {os: windows-latest, node-version: 15, experimental: false}
      # {os: windows-latest, node-version: 16, experimental: false}
      # {os: macos-latest, node-version: 15}
      # {os: ubuntu-latest, node-version: 17 }

      # if not included, or if setted to true, if one job fails, the others that are pending to finish will fail as well.
      fail-fast: false
      # if not specifed, all combinations run at the same time in parallel
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.experimental == true
        run: exit 1
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v
