name: Matrix
on: [push]

jobs: 
  node-matrix:
    # The strategy defines the matrix, so as many arguments are received, is the number of times the job will run
    # each time with one of the given values.
    # In the case of having more than 1 defined matrix, then the job will run with all the possible combinations.
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: node -v
