name: Pull Request Comment

on:
  pull_request_target:
    types: [ opened ]

jobs: 
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on New PRs
        uses: actions/github-script@v6
        # In order to run basic JS commands 
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Thanks  for contributing!',
            })
