name: Simple Action

on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        #giving and Id can be helpful for calling the step in another step.
        id: greet
        # @ => references the target branch from the repository
        # one can use a public repository or an specific repsoitory action by calling the user_id/repository
        uses: actions/hello-world-javascripr-action@main
        with: 
          who-to-greet: Antonio
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"