name: Stale Issued & PRs

on:
  schedule:
    # 5 fields => minute, hour, day (month), month, day(week)
    # * any value
    # , value list separator
    # - range of values
    # / step values
    # 0-6 allowed values
    # SUN-SAT alternative single values
    # ? sunday
    # for example:
      # 1,2 * * * * => it means that it will be triggered at every 1 and 2 minutes of every hour, every day, every month. 
      # 1-3 * * * * => every 1, 2 and 3 minutes of every hour, every day, every month
      # 0/15 * * * * => from minute 0 and every 15 minutes of every hour, every day, every month
      # 0 12 1 1 * => at 12:00 every 1st of January
      # 0 13 * FEB 3 => at 13:00 every Wednesday of February 
    # months and days of the week start at 0 being January and Sunday their respective 0
    - cron: "0 14 * * *"
    - cron: "0 2 * * *"
    # - cron: "0/5 * * * *" #gitHub actions only accept the stale every 5 minutes at least, it is not possible to ask for the trigger every single minute.

jobs:
  stale: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with: 
          stale-issue-message: "This is some message."
          days-before-stale: 1
          days-before-close: 5