name:  Status Check Functions

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    # It passes more minutes than the specified, then the entire job will get cancelled.
    timeout-minutes: 1
    steps:
      - name: Step 1
        run: sleep 90
        # It passes more minutes than the specified, then the step will fail.
        # timeout-minutes: 1
      # In order to make the Workflow fail
      - name: Step 2
        id: step-2
        # Prevent the entire job for failing in the case this job fails.
        continue-on-error: true
        run: exit 1
      - name: Runs on Step 2 Failure
        # Whennever the workflow fails, this step will run
        # if: failure()
        # Only when step, with id=step-2 fails, then this step will run
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Runs only on Step 2 failure'
      - name: Runs on Failure
        if: failure()
        run: echo 'Runs only on general failure'
      - name: Runs on Success
        # default, not necessary to include in a normal workflow.
        # This will be like the Default behavior
        if: success() 
        run: echo 'Runs on Success'
      - name: Always Runs
        # always() =
        # if: success() || failure()
        if: always()
        run: echo 'Always Runs'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps: 
      - run: echo 'Job 2'