name:  Status Check Functions

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on Failure
        if: failure()
        run: echo 'Runs only on failure'
      - name: Runs on Success
        # default, not necessary to include in a normal workflow.
        # This will be like the Default behavior
        if: success() 
        run: echo 'Runs on Success'
      - name: Always Runs
        # always() =
        # if: success() || failure()
        if: always()
        run: echo 'Always Runs'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps: 
      - run: echo 'Job 2'