name: Variables and Secrets

on: [push]

jobs:
  # the vars object will contain all the available variables, at all leveles, for this workflow
  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: staging
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR:  ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "I ran"
      - name: Log Vars
      # If you don't specify an environment, the ENV_LEVEL_VAR will return nothing
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"