name: Workflow Run
# In order to run a Workflow after another workflow has been completed

on: 
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
    branches:
      - main
      
jobs: 
  echo-string:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "I was trigerred because of 'Repository Events' was completed. "